import { default as djs } from "dayjs";
import advancedFormatPlugin from "dayjs/plugin/advancedFormat.js";
import calendarPlugin from "dayjs/plugin/calendar.js";
import customParseFormatPlugin from "dayjs/plugin/customParseFormat.js";
import dayOfYearPlugin from "dayjs/plugin/dayOfYear.js";
import devHelperPlugin from "dayjs/plugin/devHelper.js";
import durationPlugin from "dayjs/plugin/duration.js";
import isBetweenPlugin from "dayjs/plugin/isBetween.js";
import isLeapYearPlugin from "dayjs/plugin/isLeapYear.js";
import isoWeekPlugin from "dayjs/plugin/isoWeek.js";
import isoWeeksInYearPlugin from "dayjs/plugin/isoWeeksInYear.js";
import isTodayPlugin from "dayjs/plugin/isToday.js";
import isTomorrowPlugin from "dayjs/plugin/isTomorrow.js";
import isYesterdayPlugin from "dayjs/plugin/isYesterday.js";
import localeDataPlugin from "dayjs/plugin/localeData.js";
import localizedFormatPlugin from "dayjs/plugin/localizedFormat.js";
import minMaxPlugin from "dayjs/plugin/minMax.js";
import objectSupportPlugin from "dayjs/plugin/objectSupport.js";
import preParsePostFormatPlugin from "dayjs/plugin/preParsePostFormat.js";
import quarterOfYearPlugin from "dayjs/plugin/quarterOfYear.js";
import relativeTimePlugin from "dayjs/plugin/relativeTime.js";
import timezonePlugin from "dayjs/plugin/timezone.js";
import toObjectPlugin from "dayjs/plugin/toObject.js";
import utcPlugin from "dayjs/plugin/utc.js";
import weekdayPlugin from "dayjs/plugin/weekday.js";
import weekOfYearPlugin from "dayjs/plugin/weekOfYear.js";
import weekYearPlugin from "dayjs/plugin/weekYear.js";

djs.extend(advancedFormatPlugin);
djs.extend(calendarPlugin);
djs.extend(customParseFormatPlugin);
djs.extend(dayOfYearPlugin);
djs.extend(devHelperPlugin);
djs.extend(durationPlugin);
djs.extend(isBetweenPlugin);
djs.extend(isLeapYearPlugin);
djs.extend(isoWeekPlugin);
djs.extend(isoWeeksInYearPlugin);
djs.extend(isTodayPlugin);
djs.extend(isTomorrowPlugin);
djs.extend(isYesterdayPlugin);
djs.extend(localeDataPlugin);
djs.extend(localizedFormatPlugin);
djs.extend(minMaxPlugin);
djs.extend(objectSupportPlugin);
djs.extend(preParsePostFormatPlugin);
djs.extend(quarterOfYearPlugin);
djs.extend(relativeTimePlugin);
djs.extend(timezonePlugin);
djs.extend(toObjectPlugin);
djs.extend(utcPlugin);
djs.extend(weekdayPlugin);
djs.extend(weekOfYearPlugin);
djs.extend(weekYearPlugin);

export const dayjs = djs;
