import { default as djs } from "dayjs";
import advancedFormatPlugin from "dayjs/plugin/advancedFormat";
import calendarPlugin from "dayjs/plugin/calendar";
import customParseFormatPlugin from "dayjs/plugin/customParseFormat";
import dayOfYearPlugin from "dayjs/plugin/dayOfYear";
import devHelperPlugin from "dayjs/plugin/devHelper";
import durationPlugin from "dayjs/plugin/duration";
import isBetweenPlugin from "dayjs/plugin/isBetween";
import isLeapYearPlugin from "dayjs/plugin/isLeapYear";
import isoWeekPlugin from "dayjs/plugin/isoWeek";
import isoWeeksInYearPlugin from "dayjs/plugin/isoWeeksInYear";
import isTodayPlugin from "dayjs/plugin/isToday";
import isTomorrowPlugin from "dayjs/plugin/isTomorrow";
import isYesterdayPlugin from "dayjs/plugin/isYesterday";
import localeDataPlugin from "dayjs/plugin/localeData";
import localizedFormatPlugin from "dayjs/plugin/localizedFormat";
import minMaxPlugin from "dayjs/plugin/minMax";
import objectSupportPlugin from "dayjs/plugin/objectSupport";
import preParsePostFormatPlugin from "dayjs/plugin/preParsePostFormat";
import quarterOfYearPlugin from "dayjs/plugin/quarterOfYear";
import relativeTimePlugin from "dayjs/plugin/relativeTime";
import timezonePlugin from "dayjs/plugin/timezone";
import toObjectPlugin from "dayjs/plugin/toObject";
import utcPlugin from "dayjs/plugin/utc";
import weekdayPlugin from "dayjs/plugin/weekday";
import weekOfYearPlugin from "dayjs/plugin/weekOfYear";
import weekYearPlugin from "dayjs/plugin/weekYear";

djs.extend(advancedFormatPlugin);
djs.extend(calendarPlugin);
djs.extend(customParseFormatPlugin);
djs.extend(dayOfYearPlugin);
djs.extend(devHelperPlugin);
djs.extend(durationPlugin);
djs.extend(isBetweenPlugin);
djs.extend(isLeapYearPlugin);
djs.extend(isoWeekPlugin);
djs.extend(isoWeeksInYearPlugin);
djs.extend(isTodayPlugin);
djs.extend(isTomorrowPlugin);
djs.extend(isYesterdayPlugin);
djs.extend(localeDataPlugin);
djs.extend(localizedFormatPlugin);
djs.extend(minMaxPlugin);
djs.extend(objectSupportPlugin);
djs.extend(preParsePostFormatPlugin);
djs.extend(quarterOfYearPlugin);
djs.extend(relativeTimePlugin);
djs.extend(timezonePlugin);
djs.extend(toObjectPlugin);
djs.extend(utcPlugin);
djs.extend(weekdayPlugin);
djs.extend(weekOfYearPlugin);
djs.extend(weekYearPlugin);

export const dayjs = djs;
